SELECT * FROM TIMEOFF_REQUESTS
--EXEC DBO.TIMEOFF_REQUEST_FORM 'LWEISS','2021-10-10'

--EXEC DBO.TIMEOFF_REQUEST_FORM 'CPROVOLT','2021-08-15'
--EXEC DBO.TIMEOFF_REQUEST_FORM 'CWAYTASHEK','2021-08-18'
--EXEC DBO.TIMEOFF_REQUEST_FORM 'RMITCHELL','2021-08-09'
--EXEC DBO.TIMEOFF_REQUEST_FORM 'CTAYLOR','2021-08-08'
--EXEC DBO.TIMEOFF_REQUEST_FORM 'DMAENLE','2021-08-28'
--EXEC DBO.TIMEOFF_REQUEST_FORM 'JCROWLEY','2021-08-01'
--EXEC DBO.TIMEOFF_REQUEST_FORM 'LWEISS','2021-08-19'



--X  Chris    Aug 1 - 16   Sep 16 - 21
--XCindy    Aug 18       Sept 24 -26
--XRebecca Aug 4, 9   Sept 19th
--XChristina Aug 1 - 8th  Sept NA
--XKlara   Aug NA     Sept 25- 26
--XDaniel  Aug 14 - 28th(Secondary possible)    Sept 17 - 19
--XJason   Aug 1st     Sept 10-19


--Lina   Wants Aug 27- 29 (1st) Wants 2nd 23-27,
--       Not on call - 20 - 22,         Sept 20 - 26
--       Avoid Aug 2 - 19th


SELECT * FROM TIMEOFF_REQUESTS TR
INNER JOIN DBO.PERSON P ON P.PERSON_ID = TR.PERSON_ID
RIGHT JOIN DBO.CALENDAR C ON TR.[DATE_OF_REQUEST] = C.THEDATE
WHERE C.THEYEAR = 2021
AND C.THEMONTHNAME = 'AUGUST'


		SELECT * FROM DBO.CALENDAR
		WHERE THEMONTHNAME = 'AUGUST'


/*
CREATE PROCEDURE CLEANUP_REQUESTS @PERSONID INT , @DATEINQUESTION DATE 
AS
*/
GO
DECLARE @PERSONID INT = 3
DECLARE @DATEINQUESTION DATE = '2021-08-18'

DECLARE @THEISOWEEKNUM TINYINT
DECLARE @THEDAYOFWEEK TINYINT




GO
DROP SEQUENCE DBO.SEQ_GROUPNUMBER
CREATE SEQUENCE DBO.SEQ_GROUPNUMBER
    START WITH 1 INCREMENT BY 1 ;  
GO  
--LOGIC ISN'T HANDLING NEWYEARS ON A HALF DONE GROUP NUMBER
DECLARE @WEEKNUM INT = 1
DECLARE @GROUPNUM INT
DECLARE @YEARNUM DATE = (SELECT MIN(THEDATE) FROM DBO.CALENDAR)
DECLARE @YEARNUMPART INT = DATEPART(YEAR,@YEARNUM)
DECLARE @MAXYEAR DATE = (SELECT MAX(THEDATE) FROM DBO.CALENDAR)
DECLARE @MAXYEARPART INT = DATEPART(YEAR,@MAXYEAR)
WHILE (SELECT COUNT(*) FROM DBO.CALENDAR WHERE GROUPNUMBER IS NULL) > 0
BEGIN

	WHILE @WEEKNUM < 54
	BEGIN

	SET @GROUPNUM  = NEXT VALUE FOR SEQ_GROUPNUMBER
		UPDATE C 
		SET C.GROUPNUMBER = @GROUPNUM
		FROM DBO.CALENDAR C
		WHERE C.THEWEEKNUM = @WEEKNUM
			AND C.THEDAYOFWEEK IN (1,2,3,4)
			AND C.THEYEAR = @YEARNUMPART

	SET @GROUPNUM  = NEXT VALUE FOR SEQ_GROUPNUMBER

		UPDATE C 
		SET C.GROUPNUMBER = @GROUPNUM
		FROM DBO.CALENDAR C
		WHERE C.THEWEEKNUM = @WEEKNUM
			AND C.THEDAYOFWEEK IN (5,6,7)
			AND C.THEYEAR = @YEARNUMPART

	SET @WEEKNUM  = @WEEKNUM +1
	END
	SET @WEEKNUM = 1 
	SET @YEARNUMPART = @YEARNUMPART +1
END
