USE FOO;
GO
SET NOCOUNT ON
IF EXISTS ( SELECT 1 FROM SYS.TABLES WHERE NAME = 'PERSON')
BEGIN
	DROP TABLE DBO.PERSON
END
GO
CREATE TABLE DBO.PERSON
(
	PERSON_ID INT IDENTITY(1,1) PRIMARY KEY,
	PERSON_NAME VARCHAR(30) NOT NULL,
	PERSON_TEAM VARCHAR(30) NOT NULL,
	PERSON_PHONE VARCHAR(30) NULL,
	PERSON_EMAIL VARCHAR(50) NOT NULL,
	IS_ACTIVE BIT NOT NULL

)

GO
INSERT INTO PERSON (PERSON_NAME,PERSON_TEAM,PERSON_EMAIL, IS_ACTIVE)
VALUES ('CHRIS PROVOLT','COBALT','CPROVOLT',1);
INSERT INTO PERSON (PERSON_NAME,PERSON_TEAM,PERSON_EMAIL, IS_ACTIVE)
VALUES ('CHRISTINA TAYLOR','COBALT','CTAYLOR',1);
INSERT INTO PERSON (PERSON_NAME,PERSON_TEAM,PERSON_EMAIL, IS_ACTIVE)
VALUES ('CINDY WAYTASHEK','COBALT','CWAYTASHEK',1);
INSERT INTO PERSON (PERSON_NAME,PERSON_TEAM,PERSON_EMAIL, IS_ACTIVE)
VALUES ('DANIEL MAENLE','COBALT','DMAENLE',1);
INSERT INTO PERSON (PERSON_NAME,PERSON_TEAM,PERSON_EMAIL, IS_ACTIVE)
VALUES ('JASON CROWLEY','COBALT','JCROWLEY',1);
INSERT INTO PERSON (PERSON_NAME,PERSON_TEAM,PERSON_EMAIL, IS_ACTIVE)
VALUES ('KLARA TOWNSEND','COBALT','KTOWNSEND',1);
INSERT INTO PERSON (PERSON_NAME,PERSON_TEAM,PERSON_EMAIL, IS_ACTIVE)
VALUES ('LINA WEISS','COBALT','LWEISS',1);
INSERT INTO PERSON (PERSON_NAME,PERSON_TEAM,PERSON_EMAIL, IS_ACTIVE)
VALUES ('REBECCA MITCHELL','COBALT','RMITCHELL',1);


