USE FOO;
GO
SET NOCOUNT ON
IF EXISTS ( SELECT 1 FROM SYS.TABLES WHERE NAME = 'TIMEOFF_REQUESTS')
BEGIN
	DROP TABLE DBO.TIMEOFF_REQUESTS
END
GO
CREATE TABLE DBO.[TIMEOFF_REQUESTS]
(
	[ID] INT IDENTITY(1,1) PRIMARY KEY,
	[DATE_OF_REQUEST] DATE NOT NULL,
	PERSON_ID INT NOT NULL,
	PRIMARY_REQ BIT NOT NULL DEFAULT CAST(0 AS BIT),
	SECONDARY_REQ BIT NOT NULL DEFAULT CAST(0 AS BIT) ,
	TYPE_OF_REQUEST CHAR(3) NOT NULL, -- ON OR OFF
	DATE_REQUESTED DATE DEFAULT  GETDATE()
	FOREIGN KEY (PERSON_ID) REFERENCES DBO.PERSON(Person_ID),
	CONSTRAINT UC_REQUEST_PERSON UNIQUE(DATE_OF_REQUEST,PERSON_ID)
)

GO


CREATE OR ALTER PROCEDURE DBO.TIMEOFF_REQUEST_FORM
@PERSON_EMAIL VARCHAR(50), @DATE_OF_REQUEST DATE , @TYPE_OF_REQUEST CHAR(3) = 'OFF', @PRIMARY_REQ BIT = 0, @SECONDARY_REQ BIT = 0
AS
BEGIN
	SET NOCOUNT ON
	IF NOT EXISTS (SELECT 1 FROM DBO.PERSON WHERE PERSON_EMAIL = @PERSON_EMAIL)
		BEGIN
			RAISERROR (15600,16,-1,'PERSON DOES NOT EXIST, PLEASE CHECK INPUT FOR @PERSON_EMAIL')
			RETURN
		END
	IF @TYPE_OF_REQUEST NOT IN ('ON', 'OFF')
		BEGIN
			RAISERROR (15600,16,-1,'TYPE OF REQUEST NOT VALID, PLEASE CHECK INPUT FOR @TYPE_OF_REQUEST, EITHER ON OR OFF')
			RETURN

		END
	DECLARE @PERSONID INT 
		SELECT @PERSONID = PERSON_ID FROM DBO.PERSON WHERE PERSON_EMAIL = @PERSON_EMAIL

	INSERT INTO DBO.[TIMEOFF_REQUESTS]
		(DATE_OF_REQUEST,PERSON_ID,TYPE_OF_REQUEST,PRIMARY_REQ,SECONDARY_REQ)
	VALUES(@DATE_OF_REQUEST,@PERSONID,@TYPE_OF_REQUEST, @PRIMARY_REQ, @SECONDARY_REQ)


END

